### ISSUE TITLE
bug: compatible with metrics 0.23

### ISSUE THREAD

**Issue by MrCroxx** [instrumentisto/metrics-prometheus-rs#10]
## Summary

Thank you for the great lib. I was using `metrics = "0.22"` with `metrics-prometheus = "0.6"`, they worked well. But after I upgrade `metrics` to `0.23`, all data of my metrics are gone.

## Steps to reproduce

Use version `0.6` with `metrics 0.23`

## What is the current _bug_ behavior?

Cannot get my metrics data like with metrics 0.22

**Comment by tyranron** [comment]
@MrCroxx yup, you cannot use it with `0.23` version of `metrics`, since it's a breaking change in dependencies. I'll release migration to new version shortly.

**Comment by tyranron** [comment]
And yes, @dependabot is lazy bastard...

**Comment by tyranron** [comment]
Released as [0.7.0](https://crates.io/crates/metrics-prometheus/0.7.0).
Enjoy.

**Comment by MrCroxx** [comment]
Oh, thank you very much, @tyranron . That's a really fast response. 🥰
