### ISSUE TITLE
BlueOak license

### ISSUE THREAD

**Issue by emk** [instrumentisto/metrics-prometheus-rs#8]
Related to https://github.com/github/choosealicense.com/issues/816.

Thank you for writing a great integration library for `metrics` and `prometheus`!

## Background

When I ran our license checker, I noticed that `metrics-prometheus` used the BlueOak 1.0.0 license:

```
cargo deny check
error[L001]: failed to satisfy license requirements
  ┌─ metrics-prometheus 0.4.1 (registry+https://github.com/rust-lang/crates.io-index):4:12
  │
4 │ license = "BlueOak-1.0.0"
  │            ^^^^^^^^^^^^^
```

As far I can tell, this license does not appear on the [OSI approved license list](https://opensource.org/licenses/) or the [Free Software Foundation license list](https://www.gnu.org/licenses/license-list.html). This means that if we want to use `metrics-prometheus`, we would probably need to pay a lawyer to review the license, or wait until either the OSI or the FSF finishes their review (which may take a while). Also, without FSF approval, I'm not sure whether libraries using BlueOak should be linked into programs under the GPL.

## Question

Do you feel particularly strongly about using the Blue Oak license? If so, no problem! You should use whatever license you want. (And I can always write my own `metrics` plugin for Prometheus.)

Or would you be willing to consider dual licensing `metrics-prometheus` under a more common open source license? For example, much of the Rust project uses:

```toml
license = "Apache-2.0 OR MIT"
```

If you wanted to dual-license your project, you could use something like:

```toml
license = "BlueOak-1.0.0 OR Apache-2.0"
# Or
license = "BlueOak-1.0.0 OR Apache-2.0 OR MIT"
```

But once again, it's your library, and you should of course license it however you prefer.

Once again, thanking you for writing a very helpful library!

**Comment by emk** [comment]
Oh, and please feel free to close this issue!

I went ahead this afternoon and wrote a basic `metrics` backend for Prometheus. (`metrics-exporter-prometheus` wasn't a viable choice because it doesn't handle "push gateway" support in a way that works reliably for batch jobs.)

**Comment by tyranron** [comment]
@emk I've used `BlueOak-1.0.0`, because it's just handy and clearly understandable. If it imposes integration problems for downstream crates, I don't mind changing it.

**Comment by tyranron** [comment]
@emk relicensed as "Apache-2.0 OR MIT" and released as [0.5.0](https://github.com/instrumentisto/metrics-prometheus-rs/releases/tag/v0.5.0).

**Comment by emk** [comment]
Oh, thank you so very much! That will make my life easier.

The next time I update [opinionated_telemetry](https://docs.rs/opinionated_telemetry/latest/opinionated_telemetry/), I'll look at setting `metrics-prometheus` up again! Right now, I'm using a very basic custom implementation [here](https://github.com/dbcrossbar/dbcrossbar/blob/main/crates/opinionated_telemetry/src/prometheus_recorder.rs) and [here](https://github.com/dbcrossbar/dbcrossbar/blob/main/crates/opinionated_telemetry/src/metrics_support.rs). You implementation is much faster when using frozen metric sets, because I'm just doing the bare minimum with lots of `Arc`.

**Comment by sskras** [comment]
FWIW, BlueOak model license got approved by OSI just now: https://github.com/spdx/license-list-XML/issues/2352

**Comment by emk** [comment]
Ah, that's great news for fans of BlueOak! Thank you for letting me know.
